# Site settings
title: "qcao"
description: "Sweet love stories."
baseurl: ""
url: "http://qcao.us"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 5

# Links
links:
  - title: "abt"
    url: /about
